trans_map = {
    # biz/exception
    "Data does not exist": "数据不存在",
    "The data is referenced and cannot be deleted": "数据被引用，不能删除",
    "Prohibit manipulation of the data": "禁止操作该数据",
    "Server exception, please try again later": "服务器异常，请稍后重试",
    "Signature error": "签名错误",
    "Duplicate data configuration": "数据配置重复",
    "Data cannot be deleted": "数据不能删除",
    "The current data volume is large, please use the asynchronous export function": "当前数据量较大，请使用异步导出功能",
    "The current data volume is large, and it has been automatically switched to use asynchronous export": "当前数据量较大，已经自动切换使用异步导出",
    "Data update failed": "数据更新失败",
    "data error": "数据错误",
    "The bill is processed and cannot be modified or deleted": "账单被处理，不能修改或删除",
    "The bill is processed and cannot be processed again": "账单被处理，不能再次处理",
    "Cannot modify merchant configuration data": "不能修改商户配置数据",
    "Duplicate domain name": "域名重复",
    "No domain name available, please add a backup library": "无可用域名，请添加备用库",
    "The brand already exists, please do not repeat configuration": "品牌已存在，请勿重复配置",
    "Already available configuration": "已有可用配置",
    "Missing parameters": "缺少参数",
    "The number of brands has exceeded the standard": "品牌数量已超标",
    "pay type already exists": "pay type 已存在",
    "Mail has been viewed and cannot be operated": "邮件已查看，不能操作",
    "Bulk emails have not been sent, please try again later": "批量邮件未发送完，请稍后再操作",
    "Single upper and lower limits must be multiples of base": "单笔上下限必需为base的倍数",
    "A single amount exceeds the limit": "单笔金额超过限制",
    "A single day amount exceeds the limit": "单日金额超过限制",
    "The number of times in a single day exceeds the limit": "单日次数超过限制",
    "User does not exist": "用户不存在",
    "Cannot add ALPHA data": "不能新增ALPHA数据",
    "Cannot modify ALPHA data": "不能修改ALPHA数据",
    "Cannot disable BRAVO data": "不能禁用BRAVO数据",
    "Data has been disabled and cannot be operated": "数据已被禁用，不能操作",
    "Cannot delete ALPHA data": "不能删除ALPHA数据",
    "The data is not in a disabled state and cannot be lifted": "数据不是禁用状态，不能解禁",
    "Can't unbind mobile phone number": "不能解绑手机号",
    "No user binding information found": "没有找到用户绑定信息",
    "Please enter at least one of user ID, account number, and name": "请输入用户ID、账号、姓名中至少一项",
    "Order has been locked": "订单已被锁定",
    "Incorrect order review status": "订单审核状态错误",
    "Order status error": "订单状态错误",
    "The order has arrived": "订单已到账",
    "Order appealing": "订单申诉中",
    "Data error, please resubmit": "数据错误，请重新提交",
    "mf payment orders cannot be pre-paid": "秒付订单不能预加币",
    "Order has been reviewed": "订单已被审核",
    "The payment method is not JP payment": "支付方式不是属于JP支付",
    "Blacklist already exists": "黑名单已存在",
    "Redeem code prefix is repeated": "兑换码前缀重复",
    "The redemption code has been used and cannot be deleted": "兑换码已被使用，不能删除",
    "Activity completed": "活动已完成",
    "Data reviewed": "数据已审核",
    "Event has started and cannot be edited": "活动已开始，不能编辑",
    "The task has not expired and cannot be deleted": "任务未过期，不能删除",
    "Incorrect props id": "道具ID出错",
    "The task has not finished and cannot be deleted": "活动进行中，无法删除",
    # peach/admin/exceptions
    "Illegal parameters": "参数错误",
    "Incorrect password": "密码不正确",
    "The old and new passwords cannot be the same": "新旧密码不能相同",
    "User has been disabled": "用户已被禁用",
    "Unauthorized user": "未授权用户",
    "Username already exists": "用户名已存在",
    "Role does not exist": "角色不存在",
    "Duplicate role name": "角色名称重复",
    "Bound permissions have sub-permissions": "绑定的权限具有子权限",
    "The permission has no attributes to set": "该权限没有属性可设置",
    "The role has an associated account and cannot be deleted": "角色有关联账号，不能删除",
    "Permission does not exist": "权限不存在",
    "Unauthorized operation": "未授权操作",
    "Permission already exists": "权限已经存在",
    "Verification code is empty": "验证码为空",
    "Verification code error": "验证码错误",
    "Token is invalid": "Token无效",
}
